### ISSUE TITLE
LoginRedirect and LoginPop does not work

### ISSUE THREAD

**Issue by santanp** [Azure-Samples/ms-identity-b2c-javascript-spa#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] question
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run application and sign-in. The application is not able to retrieve access_token with authorization_code grant_type

### Any log messages given by the failure
>
Error : 
```
FetchClient.ts:40 POST https://TENANT_NAME.b2clogin.com/TENANT_NAME.onmicrosoft.com/b2c_1/oauth2/v2.0/token 400 (Bad Request)
(anonymous) @ FetchClient.ts:40
step @ msal-browser.js:80
(anonymous) @ msal-browser.js:61
(anonymous) @ msal-browser.js:54
__awaiter @ msal-browser.js:50
FetchClient.sendPostRequestAsync @ FetchClient.ts:38
(anonymous) @ index.es.js:3332
step @ index.es.js:74
(anonymous) @ index.es.js:55
(anonymous) @ index.es.js:48
__awaiter$1 @ index.es.js:44
NetworkManager.sendPostRequest @ index.es.js:3326
(anonymous) @ index.es.js:3408
step @ index.es.js:74
(anonymous) @ index.es.js:55
(anonymous) @ index.es.js:48
__awaiter$1 @ index.es.js:44
BaseClient.executePostToTokenEndpoint @ index.es.js:3404
(anonymous) @ index.es.js:4722
step @ index.es.js:74
(anonymous) @ index.es.js:55
fulfilled @ index.es.js:45
Promise.then (async)
step @ index.es.js:47
(anonymous) @ index.es.js:48
__awaiter$1 @ index.es.js:44
AuthorizationCodeClient.executeTokenRequest @ index.es.js:4708
(anonymous) @ index.es.js:4647
step @ index.es.js:74
(anonymous) @ index.es.js:55
(anonymous) @ index.es.js:48
__awaiter$1 @ index.es.js:44
AuthorizationCodeClient.acquireToken @ index.es.js:4638
(anonymous) @ RedirectHandler.ts:89
step @ msal-browser.js:80
(anonymous) @ msal-browser.js:61
(anonymous) @ msal-browser.js:54
__awaiter @ msal-browser.js:50
RedirectHandler.handleCodeResponse @ RedirectHandler.ts:60
(anonymous) @ ClientApplication.ts:259
step @ msal-browser.js:80
(anonymous) @ msal-browser.js:61
fulfilled @ msal-browser.js:51
Promise.then (async)
step @ msal-browser.js:53
(anonymous) @ msal-browser.js:54
__awaiter @ msal-browser.js:50
ClientApplication.handleHash @ ClientApplication.ts:246
(anonymous) @ ClientApplication.ts:178
step @ msal-browser.js:80
(anonymous) @ msal-browser.js:61
(anonymous) @ msal-browser.js:54
__awaiter @ msal-browser.js:50
ClientApplication.handleRedirectResponse @ ClientApplication.ts:159
(anonymous) @ ClientApplication.ts:124
step @ msal-browser.js:80
(anonymous) @ msal-browser.js:61
(anonymous) @ msal-browser.js:54
__awaiter @ msal-browser.js:50
ClientApplication.handleRedirectPromise @ ClientApplication.ts:120
(anonymous) @ authRedirect.js:9
authRedirect.js:12 ServerError: invalid_request: undefined - [undefined]: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
Correlation ID: 0f55ecf0-cf8c-499a-b34f-819da33a5dbc
Timestamp: 2020-12-17 15:01:45Z
 - Correlation ID: undefined - Trace ID: undefined
    at ServerError.AuthError [as constructor] (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:216:28)
    at new ServerError (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:3319:32)
    at ResponseHandler.validateTokenResponse (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:4508:23)
    at AuthorizationCodeClient.<anonymous> (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:4759:45)
    at step (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:181:27)
    at Object.next (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:162:57)
    at fulfilled (https://alcdn.msftauth.net/browser/2.7.0/js/msal-browser.js:152:62)
```

### Expected/desired behavior
> Should get successful response for authorization_code grant_type

### Browser and version?
> Edge

### Versions
> "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4287.0 Safari/537.36 Edg/88.0.673.0"

### Mention any other details that might be useful

This is sample request which is made
`curl 'https://TENANT_NAME.b2clogin.com/TENANT_NAME.onmicrosoft.com/b2c_1/oauth2/v2.0/token' \
  -H 'content-type: application/x-www-form-urlencoded;charset=utf-8' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:6420' \
  -H 'Referer: http://localhost:6420/' \
  --data-raw 'client_id=CLIENT_ID&redirect_uri=http%3A%2F%2Flocalhost%3A6420&scope=openid%20https%3A%2F%2F<TENANT_NAME>.onmicrosoft.com%2FB2C_1%2Fdemo.read%20profile&code=LONG_CODE&code_verifier=CODE_VERIFIER&grant_type=authorization_code&client_info=1&client-request-id=652b426c-7223-4c37-9dec-7fdfb0df3951' \
  --compressed`

When I tried with adding client_secret using postman it worked and returned id_token

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@santanp apologies for late response. This is a public client app using auth code with PKCE, so you should not be needing `client_secret`. Can you confirm that you've followed the [registration steps](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa#register-the-client-app-javascript-spa) correctly? If so, can you share your [application manifest](https://docs.microsoft.com/azure/active-directory/develop/reference-app-manifest) (masking your credentials)?

**Comment by santanp** [comment]
Thanks @derisen I followed the registration steps you shared and I was able to get the required tokens using auth code with PKCE flow. 

 I had another question not related to current issue, It was regarding using custom domain for sign-in\sign-up. It would be great if you could help. I see that sign-in\sign-up always give domain with `https://<tenant-name>.b2clogin.com` I wanted to apply custom domain for our website. I went through few articles online where its mentioned its part of future roadmap. But I came across Microsoft example in documentation `https://docs.microsoft.com/en-us/azure/active-directory-b2c/overview` where they have applied custom domain `https://login.woodgrovedemo.com`. 

Ref Link : 
https://woodgrovedemo.com/Account/LogIn

**Comment by derisen** [comment]
@santanp no worries : ) Customer owned domains is a feature that is coming along, but its not here yet unfortunately ([see this](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15334317-customer-owned-domains)). Woodgrove is a one-off scenario probably made for demo purpose.

Of course, there might be a way of getting around this using CNAME, but I'm not aware of any suggestion from Microsoft.

**Comment by santanp** [comment]
Thanks again @derisen for all the help. Would love to see custom domain feature soon.
