### ISSUE TITLE
Update sample to include iframes and next.js

### ISSUE THREAD

**Issue by nataliahering** [Azure-Samples/ms-identity-b2c-javascript-spa#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] question
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Since the support for iframes and custom domains are in public preview, is there a plan to update the SPA samples, to include also the iframe solution (instead of the redirect/popup)? 

Also, given that there is a MSAL sample for next.js (https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample) is there a plan to add a specific example on how to integrate Next.js with B2C? 

Thanks a lot!!

**Comment by derisen** [comment]
@nataliahering apologies for the delay! A sample demonstrating usage within iframe was on the backlog for a while, I'll try to prioritize it in the coming weeks (however, no ETA for the moment -sorry).

For a Next.js B2C sample, we can certainly consider that. Let me discuss this and get back to you. If you run into problems when integrating B2C, you can raise an issue for that as well.

**Comment by nataliahering** [comment]
@derisen thanks a lot for the reply!! The next.js B2C specific sample would indeed be super useful, as we will be integrating soon b2c with an existing next.js spa.

**Comment by derisen** [comment]
@nataliahering no worries! Just realized that we actually have a [next.js aad sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample) and a [react b2c sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample) (or [alternatively](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/1-Authentication/2-sign-in-b2c)), so you should be able adapt the [next.js aad sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample) according to your needs.

Let me know if you run into any problems, and feel free to raise an issue at the [msal.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues).

**Comment by nataliahering** [comment]
Right, thanks a lot @derisen ! Do you have a rough timeline for the first iframe sample?

**Comment by derisen** [comment]
@nataliahering sorry for the late response. We will line up the work for sometime roughly within early May. Location is not decided yet but I'll make sure to tag you once ready. Closing this for now as no further action to take at the moment.

**Comment by derisen** [comment]
@nataliahering sorry this took so long, but you can now find the guidance on [using MSAL.js in iframed apps here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/iframe-usage.md). Hope this helps.
