### ISSUE TITLE
Redirects to my app inside the popup

### ISSUE THREAD

**Issue by conor909** [Azure-Samples/ms-identity-b2c-javascript-spa#15]
After logging in it redirects to my app inside the popup.  Is this correct?  I'd imagine anyone would want the popup to go away and my SPA to change route to authenticated content.

In the docs can you explain how to communicate with the popup, so after successful logins we can handle redirects within our app.

<img width="841" alt="Screenshot 2021-05-21 at 15 07 09" src="https://user-images.githubusercontent.com/2417359/119150350-44391200-ba46-11eb-8754-0c7237854cb2.png">

**Comment by derisen** [comment]
@conor909 apologies for late response! This is definitely not correct.

As a first step, can you update your msal version in `index.html`? You can find the [CDN links here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md#sri-hash-history)

After that, if the issue persists, can you please share your msal configuration details and also any logs that appear in browser console? This issue sometimes occur in some apps where redirect uri is set to a page that invokes msal's popup API.

**Comment by derisen** [comment]
@conor909 any updates? does the issue persists?

**Comment by derisen** [comment]
Closing, let us know if you need further help
