### ISSUE TITLE
Please inline configuration instead of breaking it out into small, separate files

### ISSUE THREAD

**Issue by JayDouglass** [Azure-Samples/ms-identity-b2c-javascript-spa#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] question
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
Breaking configuration out into separate files makes the code harder to read, because file navigation is required. There isn't much configuration data so decomposing it into smaller files hurts readability instead of improving it. 

For example authConfig.js, apiConfig.js, and policies.js could be all be wrapped up into one file.

### Browser and version?
>

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@JayDouglass apologies for late response. We have devised the folder structure this way initially as a suggestion since these configuration files can expand significantly in actual usage. We'll take your feedback into consideration when updating the sample next time. Thanks!

**Comment by derisen** [comment]
Closing this for now, as no action to take at the moment.
