### ISSUE TITLE
[Question] Login required when app is open on separate tabs in Safari Private browsing windows

### ISSUE THREAD

**Issue by JJHakiLe** [Azure-Samples/ms-identity-b2c-javascript-spa#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] question
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Description
 After following the guide and registering my azure ad b2c tenant and application with the config files, i began testing SSO on different browsers. All seems to work fine except for an issue on Safari Private browsing windows. 

While having the application open on two tabs, after authenticating in one tab, attempting to authenticate on the second tab required inputting credentials once again. I was just wondering if this is expected behavior for msal library, and if not, what might be a way to mitigate this issue? Thanks!

### Minimal steps to reproduce
> Go to the [quickstart app](https://azure-samples.github.io/ms-identity-b2c-javascript-spa/)
> Open the app on two separate tabs in Safari Private Browsing Mode
> Authenticate on the first tab
> Navigate to the second tab
> Notice that credentials are required, even though authentication was done in first tab 

### Any log messages given by the failure
>

### Expected/desired behavior
> Hopefully SSO is maintained when having the application open in two separate tabs

### Browser and version?
> Safari Version 14, Private Browsing Mode

### Versions
> "msal": "2.1.0"

### Mention any other details that might be useful
I noticed that while no log messages are given because it is technically not a failure, it seems that Azure AD B2C does not retain the session in Safari Private Browsing Mode. That may/may not be accurate so any help is appreciated

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@JJHakiLe apologies for the dealy. Unfortunately, this is expected. `ssoSilent` is using iframes and 3rd party cookies which is getting blocked here. From the [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md):

> `ssoSilent` will not work in browsers that disable 3rd party cookies, such as Safari. If you need to support these browsers, call `acquireTokenRedirect` or `acquireTokenPopup`

Here's a bit more on the cause of this issue:
- [Known issue on Safari](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari)
- [Handle ITP in Safari and other browsers where third-party cookies are blocked](https://docs.microsoft.com/azure/active-directory/develop/reference-third-party-cookies-spas)

Please track [this thread](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2499) and also take a look at the workaround offered there.

**Comment by JJHakiLe** [comment]
@derisen I see, thank you for the clarification. I will take a look into more of the documentation then. Thanks again
