### ISSUE TITLE
Versions since 2.1.0 seem to be not returning accessToken after returning from acquireTokenSilent

### ISSUE THREAD

**Issue by mikerains** [Azure-Samples/ms-identity-b2c-javascript-spa#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] question
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
In https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa cod

1. git clone https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa.git
2. cd ms-identity-b2c-javascript-spa.git
3. npm install && npm update
4. npm start
5. In Chrome, open Dev Tools, and re-load the page so Sources are populated.
6. Navigate to authPopup.js, put a breakpoint at the line doing the acquireToken, ie:
7. return myMSALObj.acquireTokenSilent(request)
8. Sign-in with a new or existing account
9. Click Call API
10. At the breakpoint, let it run and see response.accessToken  is populated

11. Now change index.html's script tag to any version after 2.1.0 and at the breakpoint see accessToken==""

It does not go into acquireTokenSilent's catch block, it simply returns with response.accessToken==""; other fields are populated.

I also tried this in a ReactJS application using npm packages and found the same behavior, received an accessToken with MSAL 2.1.0, received empty string in later version 2.7.0

### Any log messages given by the failure
>

### Expected/desired behavior
>
accessToken to be populated.

### Browser and version?
>Chrome

### Versions
>
Version 86.0.4240.75 (Official Build) (64-bit)
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@mikerains unfortunatelly, this is a [known issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-there-no-access-token-returned-from-acquiretokensilent) with the B2C service currently being [tracked here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2315#issuecomment-706382855).

If staying with the version 2.1 for the time being is not possible, can you modify your [authConfig.js](url) file like this and see if it helps:

```javascript
// instead of requesting just the ID token (openid) at login, 
// we are requesting both ID and access token for the web API

const loginRequest = {
  scopes: ["openid", ...apiConfig.b2cScopes],
};

```

**Comment by mikerains** [comment]
Thanks @derisen .  I also found there is a FAQ with the work-around you mentioned as well as a second work-around.  Seems this is on the ADB2C IdP itself and not the MSAL-Browser.js library. Thanks again.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-there-no-access-token-returned-from-acquiretokensilent

**Comment by derisen** [comment]
@mikerains you're welcome : ) Yeah, unfortunately this is to do with B2C IdP -I will update the sample tomorrow to handle it, but hopefully it will be resolved soon so the workaround won't be needed.

**Comment by derisen** [comment]
Closing.
