### ISSUE TITLE
Auth Redirect is not working properly

### ISSUE THREAD

**Issue by chdalski** [Azure-Samples/ms-identity-b2c-javascript-spa#9]
Hi there,

the function "Acquires and access token and then passes it to the API call"
`
function passTokenToApi() {
   getTokenRedirect(tokenRequest);
   if (accessToken) {
        try {
            callApi(apiConfig.webApi, accessToken);
        } catch(error) {
            console.warn(error); 
        }
    }
}
`
in _ms-identity-b2c-javascript-spa/App/authRedirect.js_ is not working as expected.

It should be something like:
`
function passTokenToApi() {
    getTokenRedirect(tokenRequest).then(response => {
        if (response.accessToken) {
            try {
                callApi(apiConfig.webApi, response.accessToken);
            } catch (error) {
                console.warn(error);
            }
        }
    });
}
`

**Comment by derisen** [comment]
@chdalski excellent catch! Will update ASAP.

**Comment by derisen** [comment]
@chdalski I've updated the sample and the issue should be resolved, but let us know if not.
